db-connection:
  url: ${URL}
  databaseName: ${DB_NAME}
  options:
    useNewUrlParser: true
    useUnifiedTopology: true

migrationsDir: migrations
changelogCollectionName: migrations
projectName: Joras
useDefaultTransaction: false
