db-connection:
  url: mongodb://localhost:27018/users?authMechanism=DEFAULT&directConnection=true
  databaseName: testDb
  options:
    useNewUrlParser: true
    useUnifiedTopology: true

migrationsDir: src/migrations
changelogCollectionName: migrations
useDefaultTransaction: false
